server:
      port: 8081
spring:
      application:
            name: user
      profiles:
            active: "prod"
      datasource:
            url: jdbc:postgresql://localhost:5432/mirco
            username: postgres
            password: postgres
            driver-class-name: org.postgresql.Driver
            hikari:
                  maximum-pool-size: 10
                  minimum-idle: 5
      jpa:
            hibernate:
                  ddl-auto: update
            show-sql: true
            properties:
                  hibernate:
                        format_sql: true
                        dialect: org.hibernate.dialect.PostgreSQLDialect
      batch:
            initialize: always
            job:
                  enabled: false
